# Generated by Django 3.0.3 on 2020-02-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movrotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='situacao',
            field=models.CharField(choices=[('PG', 'PAGO'), ('PE', 'PENDENTE')], default='PENDENTE', max_length=2),
        ),
    ]
