# Generated by Django 3.0.3 on 2020-02-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200210_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='situacao',
            field=models.CharField(choices=[('PG', 'Pago'), ('PE', 'Pendente')], default='PE', max_length=2),
        ),
    ]
